spring.application.name=taskproject

# Database configuration (use Railway variables)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# JWT configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

# Dynamic port binding for Railway
server.port=${PORT:8080}
